In [7]:
import numpy as np

arr = np.arange(12)          # cria de 0 até 11
matriz = arr.reshape(3, 4)  # transforma em 3x4

print(matriz)

# segunda linha
print("Segunda linha:", matriz[1])

# terceira linha, quarta coluna
print("Elemento [2][3]:", matriz[2][3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Segunda linha: [4 5 6 7]
Elemento [2][3]: 11


In [8]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))
print("Concatenado:", c)

# slicing
print("Slice:", c[1:5])

Concatenado: [1 2 3 4 5 6]
Slice: [2 3 4 5]


In [9]:
import numpy as np

original = np.array([10, 20, 30, 40, 50])

copia = original.copy()

# remove o valor 30
copia = copia[copia != 30]

print("Original:", original)
print("Cópia:", copia)

Original: [10 20 30 40 50]
Cópia: [10 20 40 50]


In [10]:
import numpy as np

arr = np.array([100, 200, 300, 400, 500, 600])

parte1, parte2 = np.split(arr, 2)

# adiciona 700 na segunda parte
parte2 = np.append(parte2, 700)

print("Parte 1:", parte1)
print("Parte 2:", parte2)

Parte 1: [100 200 300]
Parte 2: [400 500 600 700]
